# Generated by Django 3.2.4 on 2021-08-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210816_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
