# Generated by Django 3.2.4 on 2021-08-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210817_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
